/**
 * Markdown Export — human-readable bundle from WorkspaceExport.
 * Produces a zip-ready Map<filename, content> of markdown files.
 * Pure functions. No I/O. No server-only required.
 */

import type { WorkspaceExport, ExportedIdea, ExportedProject, ExportedMemory } from "./types";

export type MarkdownBundle = Map<string, string>;

// ─── Main entry point ─────────────────────────────────────────────────────────

export function generateMarkdownBundle(exp: WorkspaceExport): MarkdownBundle {
  const bundle: MarkdownBundle = new Map();

  bundle.set("README.md", buildReadme(exp));
  bundle.set("ideas/index.md", buildIdeasIndex(exp.ideas));
  bundle.set("projects/index.md", buildProjectsIndex(exp.projects));
  bundle.set("memories/index.md", buildMemoriesIndex(exp.memories));

  for (const idea of exp.ideas) {
    bundle.set(`ideas/${sanitize(idea.title)}.md`, buildIdeaDoc(idea));
  }
  for (const project of exp.projects) {
    bundle.set(`projects/${sanitize(project.title)}.md`, buildProjectDoc(project));
  }
  for (const memory of exp.memories) {
    bundle.set(`memories/${memory.type.toLowerCase()}/${sanitize(memory.title)}.md`, buildMemoryDoc(memory));
  }

  return bundle;
}

// ─── README ───────────────────────────────────────────────────────────────────

function buildReadme(exp: WorkspaceExport): string {
  const counts = exp.meta.entityCounts;
  return `# WorkSpace Export

Exported: ${new Date(exp.meta.exportedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

## Contents

| Entity | Count |
|--------|-------|
| Ideas | ${counts.ideas ?? 0} |
| Projects | ${counts.projects ?? 0} |
| Memories | ${counts.memories ?? 0} |
| Strategic Reviews | ${counts.strategicReviews ?? 0} |

## Structure

\`\`\`
ideas/           — idea documents
projects/        — project documents with full execution history
memories/        — knowledge memories by type
README.md        — this file
\`\`\`

This export was generated by WorkSpace and preserves all relationships, timelines, and metadata.
To re-import, use the JSON format (\`workspace-export.json\`).
`;
}

// ─── Ideas index ─────────────────────────────────────────────────────────────

function buildIdeasIndex(ideas: ExportedIdea[]): string {
  const active   = ideas.filter((i) => i.status !== "ARCHIVED");
  const archived = ideas.filter((i) => i.status === "ARCHIVED");

  const rows = (list: ExportedIdea[]) =>
    list.map((i) =>
      `| [${esc(i.title)}](${sanitize(i.title)}.md) | ${i.readinessStatus} | ${i.tags.join(", ") || "—"} | ${fmt(i.createdAt)} |`
    ).join("\n");

  return `# Ideas

## Active (${active.length})

| Title | Status | Tags | Created |
|-------|--------|------|---------|
${rows(active)}

## Archived (${archived.length})

| Title | Status | Tags | Created |
|-------|--------|------|---------|
${rows(archived)}
`;
}

// ─── Projects index ───────────────────────────────────────────────────────────

function buildProjectsIndex(projects: ExportedProject[]): string {
  const rows = projects.map((p) =>
    `| [${esc(p.title)}](${sanitize(p.title)}.md) | ${p.status} | ${p.tasks.filter((t) => t.status === "DONE").length}/${p.tasks.length} tasks | ${fmt(p.createdAt)} |`
  ).join("\n");

  return `# Projects

| Title | Status | Progress | Created |
|-------|--------|----------|---------|
${rows}
`;
}

// ─── Memories index ───────────────────────────────────────────────────────────

function buildMemoriesIndex(memories: ExportedMemory[]): string {
  const byType = new Map<string, ExportedMemory[]>();
  for (const m of memories) {
    const list = byType.get(m.type) ?? [];
    list.push(m);
    byType.set(m.type, list);
  }

  const sections = [...byType.entries()].map(([type, list]) => {
    const rows = list.map((m) =>
      `| [${esc(m.title)}](${type.toLowerCase()}/${sanitize(m.title)}.md) | ${m.significance}/10 | ${m.projectTitle ?? m.ideaTitle ?? "—"} |`
    ).join("\n");
    return `## ${type}\n\n| Title | Significance | Context |\n|-------|-------------|--------|\n${rows}`;
  });

  return `# Knowledge Memories\n\n${sections.join("\n\n")}\n`;
}

// ─── Idea document ────────────────────────────────────────────────────────────

function buildIdeaDoc(idea: ExportedIdea): string {
  const sections: string[] = [
    `# ${idea.title}`,
    `**Status:** ${idea.readinessStatus} · **Score:** ${Math.round(idea.readinessScore)} · **Created:** ${fmt(idea.createdAt)}`,
    idea.description ? `\n${idea.description}` : "",
  ];

  if (idea.tags.length > 0) {
    sections.push(`**Tags:** ${idea.tags.join(", ")}`);
  }

  for (const block of idea.blocks) {
    if (block.content.trim()) {
      sections.push(`## ${blockLabel(block.type)}\n\n${block.content}`);
    }
  }

  if (idea.notes.length > 0) {
    const noteLines = idea.notes.map((n) =>
      n.title ? `### ${n.title}\n\n${n.content}` : n.content
    ).join("\n\n---\n\n");
    sections.push(`## Notes\n\n${noteLines}`);
  }

  if (idea.links.length > 0) {
    const linkLines = idea.links.map((l) => `- [${esc(l.label)}](${l.url})`).join("\n");
    sections.push(`## Links\n\n${linkLines}`);
  }

  return sections.filter(Boolean).join("\n\n");
}

// ─── Project document ─────────────────────────────────────────────────────────

function buildProjectDoc(project: ExportedProject): string {
  const doneTasks = project.tasks.filter((t) => t.status === "DONE").length;
  const sections: string[] = [
    `# ${project.title}`,
    `**Status:** ${project.status} · **Execution:** ${project.executionState} · **Momentum:** ${Math.round(project.momentumScore)}`,
    `**Progress:** ${doneTasks}/${project.tasks.length} tasks · **Created:** ${fmt(project.createdAt)}`,
    project.description ? `\n${project.description}` : "",
  ];

  if (project.milestones.length > 0) {
    const rows = project.milestones.map((m) =>
      `- [${m.status === "COMPLETED" ? "x" : " "}] **${esc(m.title)}** — ${m.status}`
    ).join("\n");
    sections.push(`## Milestones\n\n${rows}`);
  }

  if (project.tasks.length > 0) {
    const taskLines = project.tasks.map((t) => {
      const sub = t.subtasks.length > 0
        ? "\n" + t.subtasks.map((s) => `    - [${s.status === "DONE" ? "x" : " "}] ${esc(s.title)}`).join("\n")
        : "";
      return `- [${t.status === "DONE" ? "x" : " "}] ${esc(t.title)} _(${t.priority})_${sub}`;
    }).join("\n");
    sections.push(`## Tasks\n\n${taskLines}`);
  }

  if (project.decisions.length > 0) {
    const decLines = project.decisions.map((d) =>
      `### ${esc(d.title)}\n\n**Decision:** ${d.decision}\n\n**Context:** ${d.context || "—"}\n\n**Tradeoffs:** ${d.tradeoffs || "—"}`
      + (d.reversed ? `\n\n> ⚠️ Reversed: ${d.reversalNote ?? ""}` : "")
    ).join("\n\n---\n\n");
    sections.push(`## Decisions\n\n${decLines}`);
  }

  if (project.weeklyReviews.length > 0) {
    const reviewLines = project.weeklyReviews.slice(-4).map((r) =>
      `### Week of ${fmt(r.weekStarting)}\n\n**Moved forward:** ${r.movedForward || "—"}\n\n**Stalled:** ${r.stalled || "—"}\n\n**Rating:** ${r.overallRating}/5`
    ).join("\n\n");
    sections.push(`## Recent Weekly Reviews\n\n${reviewLines}`);
  }

  if (project.scopeItems.length > 0) {
    const buckets = ["MVP", "V1", "LATER", "EXPERIMENTAL"] as const;
    const scopeLines = buckets
      .map((b) => {
        const items = project.scopeItems.filter((s) => s.bucket === b);
        if (items.length === 0) return "";
        return `**${b}:**\n${items.map((s) => `- ${esc(s.title)}`).join("\n")}`;
      })
      .filter(Boolean)
      .join("\n\n");
    sections.push(`## Scope\n\n${scopeLines}`);
  }

  if (project.timelineEvents.length > 0) {
    const timelineLines = project.timelineEvents
      .filter((e) => ["MILESTONE_REACHED", "DECISION_MADE", "SHIPPED", "STATUS_CHANGED"].includes(e.type))
      .slice(-10)
      .map((e) => `- **${fmt(e.occurredAt)}** — ${esc(e.title)}`)
      .join("\n");
    sections.push(`## Timeline\n\n${timelineLines}`);
  }

  return sections.filter(Boolean).join("\n\n");
}

// ─── Memory document ──────────────────────────────────────────────────────────

function buildMemoryDoc(memory: ExportedMemory): string {
  return [
    `# ${memory.title}`,
    `**Type:** ${memory.type} · **Significance:** ${memory.significance}/10 · **Created:** ${fmt(memory.createdAt)}`,
    memory.projectTitle ? `**Project:** ${memory.projectTitle}` : "",
    memory.ideaTitle    ? `**Idea:** ${memory.ideaTitle}` : "",
    memory.tags.length > 0 ? `**Tags:** ${memory.tags.join(", ")}` : "",
    memory.body,
  ].filter(Boolean).join("\n\n");
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function sanitize(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 80);
}

function esc(s: string): string {
  return s.replace(/[[\]|]/g, "\\$&");
}

function fmt(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

const BLOCK_LABELS: Record<string, string> = {
  PROBLEM:              "Problem",
  USER_PAIN:            "User Pain",
  EXISTING_ALTERNATIVES: "Existing Alternatives",
  MARKET_GAP:           "Market Gap",
  CONSTRAINTS:          "Constraints",
  RISKS:                "Risks",
  ASSUMPTIONS:          "Assumptions",
  MVP_SCOPE:            "MVP Scope",
  SUCCESS_METRICS:      "Success Metrics",
  EXECUTION_PLAN:       "Execution Plan",
  MONETIZATION:         "Monetization",
  VALIDATION_STRATEGY:  "Validation Strategy",
};

function blockLabel(type: string): string {
  return BLOCK_LABELS[type] ?? type;
}
